# Generated by Django 5.1 on 2024-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_number",
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="chapter_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("book", "chapter_number")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("chapter", "section_number")},
        ),
    ]
