# Generated by Django 5.1 on 2024-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_book_number_alter_chapter_chapter_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shloka",
            name="shloka_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="audiofile",
            name="file",
            field=models.FileField(upload_to="audio/"),
        ),
    ]
