# Generated by Django 4.2.14 on 2024-10-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_slider",
            field=models.ImageField(blank=True, null=True, upload_to="book_sliders/"),
        ),
        migrations.AddField(
            model_name="shloka",
            name="chapter_slider",
            field=models.ImageField(blank=True, null=True, upload_to="chapter_slider/"),
        ),
    ]
